#!/usr/bin/env bash
#
# launch-queue.sh — open the user's terminal and start the claude-queue TUI.
#
# Usage: launch-queue.sh <session_id>
#
# Invoked by the /claude-queue slash command. Opens a new terminal window
# (macOS or Linux), running the Node TUI for the given session. If no terminal
# can be opened (headless / remote / SSH), it prints the exact command to run
# manually so the user (or Claude) can start it by hand.

set -euo pipefail

RAW_SESSION_ID="${1:-${CLAUDE_SESSION_ID:-default}}"

# Resolve the plugin root from this script's location (scripts/ -> plugin root).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
UI_DIR="${PLUGIN_ROOT}/ui"
UI_ENTRY="${UI_DIR}/queue-ui.js"

# Sanitize the session id with the SAME function the queue store and Stop hook
# use (safeSessionId), so all three resolve to the same queue file even for
# non-ASCII ids — and so the id can't carry shell/AppleScript metacharacters into
# the command we hand to the terminal below. Fall back to a byte-wise scrub if
# node is somehow unavailable.
SESSION_ID="$(node -e 'process.stdout.write(require(process.argv[1]).safeSessionId(process.argv[2]))' \
  "${SCRIPT_DIR}/lib/queue-store.js" "${RAW_SESSION_ID}" 2>/dev/null \
  || printf '%s' "${RAW_SESSION_ID}" | tr -c 'A-Za-z0-9._-' '_')"
[ -z "${SESSION_ID}" ] && SESSION_ID="default"

# Ensure the queue directory exists.
QUEUE_DIR="${CLAUDE_QUEUE_DIR:-${HOME}/.claude-queue}"
mkdir -p "${QUEUE_DIR}"

# Housekeeping: drop queue files, wrapper scripts and stray write-temps from
# sessions that haven't been touched in a week. Anything in use is mtime-fresh,
# so live sessions are never matched; ui-*.pid files are owned (and removed)
# by their UI process, so they are left alone here.
find "${QUEUE_DIR}" -maxdepth 1 -type f \
  \( -name 'open-queue-*.sh' -o -name 'queue-*.json' -o -name '*.tmp' \) \
  -mtime +7 -delete 2>/dev/null || true

# Make sure the UI's one dependency (blessed) is installed.
if [ ! -d "${UI_DIR}/node_modules/blessed" ]; then
  if command -v npm >/dev/null 2>&1; then
    ( cd "${UI_DIR}" && npm install --silent --no-audit --no-fund ) || true
  fi
fi

# ---------------------------------------------------------------------------
# Build a single-file launcher embedding everything the UI needs: the absolute
# node binary, the UI entry point, and the session id. Every terminal below is
# handed exactly ONE word — that is what makes the launch survive hostile
# launch paths:
#
#   - No terminal has to forward extra argv words to the command. macOS window
#     restoration has been observed resurrecting a previously closed terminal
#     window by re-running its command as `<file>; exit` with NO argv — which
#     used to start a queue UI silently bound to the wrong ('default') queue.
#     With the id baked into the file, even a resurrected window starts the UI
#     for the right session.
#   - The node binary is resolved here, with the caller's PATH; GUI-spawned
#     terminals don't inherit it.
#   - Nothing needs nested quoting through AppleScript.
# ---------------------------------------------------------------------------
NODE_BIN="$(command -v node || echo node)"
WRAPPER="${QUEUE_DIR}/open-queue-${SESSION_ID}.sh"
{
  printf '#!/bin/sh\n'
  printf '# Generated by claude-queue; safe to delete once the window is open.\n'
  printf 'exec "%s" "%s" "%s"\n' "${NODE_BIN}" "${UI_ENTRY}" "${SESSION_ID}"
} >"${WRAPPER}"
chmod +x "${WRAPPER}"

manual_fallback() {
  echo "claude-queue: could not open a terminal window automatically."
  echo "Run this in any terminal to open the queue UI:"
  echo
  echo "    node \"${UI_ENTRY}\" \"${SESSION_ID}\""
  echo
}

# `open` / osascript exiting 0 only means the request was delivered, not that
# the window or the UI process actually exists. Poll for a queue UI bound to
# THIS session before reporting success, so a failed launch can never claim
# the queue is ready while tasks would go nowhere. The UI's pid file is the
# precise signal (written only by the instance that won the single-instance
# claim); the pgrep check covers the brief window before the claim lands.
verify_started() {
  local i pid
  local pidfile="${QUEUE_DIR}/ui-${SESSION_ID}.pid"
  for i in $(seq 1 30); do
    pid="$(cat "${pidfile}" 2>/dev/null || true)"
    if [ -n "${pid}" ] && kill -0 "${pid}" 2>/dev/null; then
      return 0
    fi
    if pgrep -f "queue-ui\.js ${SESSION_ID}" >/dev/null 2>&1; then
      return 0
    fi
    sleep 0.2
  done
  return 1
}

open_macos() {
  # Drive the terminal the user is already in; anything else gets Terminal.app.
  # Each branch dispatches its launch request and returns — deliberately
  # WITHOUT falling through to another terminal on a nonzero exit. `open -n`
  # has been seen exiting nonzero while the window still appears, and a
  # fall-through then opens a SECOND identical queue window in Terminal.app.
  # verify_started() is the one arbiter of success; if the dispatch truly did
  # nothing, the caller shows the manual fallback instead of guessing again.
  case "${TERM_PROGRAM:-}" in
    ghostty)
      # Ghostty has no scripting interface on macOS, so a fresh instance with
      # `-e <wrapper>` is the only programmatic window available. The single
      # wrapper word sidesteps multi-arg quirks; -F (open fresh, an `open`
      # flag) and --window-save-state=never (a Ghostty flag) both keep this
      # throwaway instance from saving or restoring windows that macOS would
      # otherwise "restore" as zombie queue windows.
      open -na Ghostty -F --args --window-save-state=never -e "${WRAPPER}" >/dev/null 2>&1
      return 0
      ;;
    iTerm.app)
      osascript >/dev/null 2>&1 <<EOF
tell application "iTerm"
  create window with default profile
  tell current session of current window to write text "\"${WRAPPER}\""
end tell
EOF
      return 0
      ;;
  esac
  # Default to Terminal.app.
  osascript >/dev/null 2>&1 <<EOF
tell application "Terminal"
  activate
  do script "\"${WRAPPER}\""
end tell
EOF
}

open_linux() {
  # No display → opening a GUI terminal would silently fail; use the manual
  # fallback instead (covers headless boxes and plain SSH sessions).
  if [ -z "${DISPLAY:-}" ] && [ -z "${WAYLAND_DISPLAY:-}" ]; then
    return 1
  fi

  # A new interactive shell so the TUI has a controlling terminal; keep it open
  # if node exits so the user can read any message.
  local sh_cmd="\"${WRAPPER}\"; echo; echo '[claude-queue UI closed]'; exec \${SHELL:-bash}"

  # Honor an explicit preference first.
  if [ -n "${TERMINAL:-}" ] && command -v "${TERMINAL}" >/dev/null 2>&1; then
    "${TERMINAL}" -e bash -lc "${sh_cmd}" >/dev/null 2>&1 & return 0
  fi

  local term
  for term in x-terminal-emulator gnome-terminal konsole xfce4-terminal kitty alacritty xterm; do
    if command -v "${term}" >/dev/null 2>&1; then
      case "${term}" in
        gnome-terminal)
          "${term}" -- bash -lc "${sh_cmd}" >/dev/null 2>&1 & return 0 ;;
        *)
          "${term}" -e bash -lc "${sh_cmd}" >/dev/null 2>&1 & return 0 ;;
      esac
    fi
  done
  return 1
}

case "$(uname -s)" in
  Darwin)
    if open_macos && verify_started; then
      echo "claude-queue: opened the queue UI for session ${SESSION_ID}."
    else
      manual_fallback
    fi
    ;;
  Linux)
    if open_linux && verify_started; then
      echo "claude-queue: opened the queue UI for session ${SESSION_ID}."
    else
      manual_fallback
    fi
    ;;
  *)
    manual_fallback
    ;;
esac
