#!/usr/bin/env bash
#
# launch-queue.sh — open the user's terminal and start the claude-queue TUI.
#
# Usage: launch-queue.sh <session_id>
#
# Invoked by the /claude-queue slash command. Opens a new terminal window
# (macOS or Linux), running the Node TUI for the given session. If no terminal
# can be opened (headless / remote / SSH), it prints the exact command to run
# manually so the user (or Claude) can start it by hand.

set -euo pipefail

RAW_SESSION_ID="${1:-${CLAUDE_SESSION_ID:-default}}"

# Resolve the plugin root from this script's location (scripts/ -> plugin root).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
UI_DIR="${PLUGIN_ROOT}/ui"
UI_ENTRY="${UI_DIR}/queue-ui.js"

# Sanitize the session id with the SAME function the queue store and Stop hook
# use (safeSessionId), so all three resolve to the same queue file even for
# non-ASCII ids — and so the id can't carry shell/AppleScript metacharacters into
# the command we hand to the terminal below. Fall back to a byte-wise scrub if
# node is somehow unavailable.
SESSION_ID="$(node -e 'process.stdout.write(require(process.argv[1]).safeSessionId(process.argv[2]))' \
  "${SCRIPT_DIR}/lib/queue-store.js" "${RAW_SESSION_ID}" 2>/dev/null \
  || printf '%s' "${RAW_SESSION_ID}" | tr -c 'A-Za-z0-9._-' '_')"
[ -z "${SESSION_ID}" ] && SESSION_ID="default"

# Ensure the queue directory exists.
QUEUE_DIR="${CLAUDE_QUEUE_DIR:-${HOME}/.claude-queue}"
mkdir -p "${QUEUE_DIR}"

# Housekeeping: drop queue files, wrapper scripts and stray write-temps from
# sessions that haven't been touched in a week. Anything in use is mtime-fresh,
# so live sessions are never matched; ui-*.pid files are owned (and removed)
# by their UI process, so they are left alone here.
find "${QUEUE_DIR}" -maxdepth 1 -type f \
  \( -name 'open-queue-*.sh' -o -name 'queue-*.json' -o -name '*.tmp' \) \
  -mtime +7 -delete 2>/dev/null || true

# Make sure the UI's one dependency (blessed) is installed.
if [ ! -d "${UI_DIR}/node_modules/blessed" ]; then
  if command -v npm >/dev/null 2>&1; then
    ( cd "${UI_DIR}" && npm install --silent --no-audit --no-fund ) || true
  fi
fi

# ---------------------------------------------------------------------------
# Build a single-file launcher embedding everything the UI needs: the absolute
# node binary, the UI entry point, and the session id. Every terminal below is
# handed exactly ONE word — that is what makes the launch survive hostile
# launch paths:
#
#   - No terminal has to forward extra argv words to the command. macOS window
#     restoration has been observed resurrecting a previously closed terminal
#     window by re-running its command as `<file>; exit` with NO argv — which
#     used to start a queue UI silently bound to the wrong ('default') queue.
#     With the id baked into the file, even a resurrected window starts the UI
#     for the right session.
#   - The node binary is resolved here, with the caller's PATH; GUI-spawned
#     terminals don't inherit it.
#   - Nothing needs nested quoting through AppleScript.
# ---------------------------------------------------------------------------
NODE_BIN="$(command -v node || echo node)"
WRAPPER="${QUEUE_DIR}/open-queue-${SESSION_ID}.sh"
{
  printf '#!/bin/sh\n'
  printf '# Generated by claude-queue; safe to delete once the window is open.\n'
  printf 'exec "%s" "%s" "%s"\n' "${NODE_BIN}" "${UI_ENTRY}" "${SESSION_ID}"
} >"${WRAPPER}"
chmod +x "${WRAPPER}"

manual_fallback() {
  echo "claude-queue: could not open a terminal window automatically."
  echo "Run this in any terminal to open the queue UI:"
  echo
  echo "    node \"${UI_ENTRY}\" \"${SESSION_ID}\""
  echo
}

# `open` / osascript exiting 0 only means the request was delivered, not that
# the window or the UI process actually exists. Poll for a queue UI bound to
# THIS session before reporting success, so a failed launch can never claim
# the queue is ready while tasks would go nowhere. The UI's pid file is the
# precise signal (written only by the instance that won the single-instance
# claim); the pgrep check covers the brief window before the claim lands.
verify_started() {
  local i pid
  local pidfile="${QUEUE_DIR}/ui-${SESSION_ID}.pid"
  # ~10s budget: a cold Terminal.app launch (app not yet running) can take a
  # few seconds before the wrapper even starts.
  for i in $(seq 1 50); do
    pid="$(cat "${pidfile}" 2>/dev/null || true)"
    if [ -n "${pid}" ] && kill -0 "${pid}" 2>/dev/null; then
      return 0
    fi
    if pgrep -f "queue-ui\.js ${SESSION_ID}" >/dev/null 2>&1; then
      return 0
    fi
    sleep 0.2
  done
  return 1
}

open_macos() {
  # iTerm users get a native iTerm window; everyone else — Terminal.app users,
  # Ghostty, unknown terminals — gets Terminal.app via `open -a`, which opens
  # the wrapper in the EXISTING Terminal instance.
  #
  # Ghostty deliberately has NO native branch. Its only programmatic window on
  # macOS is a second instance (`open -na Ghostty --args -e <wrapper>`), and
  # that instance has been observed (Ghostty 1.3.1) to pop a bogus
  # "Configuration Errors: 0 error(s)" dialog, restore stale windows that
  # re-run old wrappers as `<file>; exit`, fail to start the user's login
  # shell ("Ghostty failed to launch the requested command: /usr/bin/login …
  # fish"), and then exit half a minute after launch — taking the queue UI
  # down with it. Terminal.app hosts the queue window reliably instead.
  if [ "${TERM_PROGRAM:-}" = "iTerm.app" ]; then
    osascript >/dev/null 2>&1 <<EOF
tell application "iTerm"
  create window with default profile
  tell current session of current window to write text "\"${WRAPPER}\""
end tell
EOF
    verify_started && return 0
    # Apple Events can be unavailable (sandboxed caller, missing Automation
    # permission) — fall through to Terminal.app. Safe even if a window DID
    # open late: the UI's single-instance pid guard closes the duplicate.
  fi
  # `open -a` needs no Apple Events and no new app instance, and Terminal runs
  # the executable wrapper directly — the user's login shell (fish, zsh, bash,
  # …) never has to parse a command line.
  open -a Terminal "${WRAPPER}" >/dev/null 2>&1
}

open_linux() {
  # No display → opening a GUI terminal would silently fail; use the manual
  # fallback instead (covers headless boxes and plain SSH sessions).
  if [ -z "${DISPLAY:-}" ] && [ -z "${WAYLAND_DISPLAY:-}" ]; then
    return 1
  fi

  # A new interactive shell so the TUI has a controlling terminal; keep it open
  # if node exits so the user can read any message.
  local sh_cmd="\"${WRAPPER}\"; echo; echo '[claude-queue UI closed]'; exec \${SHELL:-bash}"

  # Honor an explicit preference first.
  if [ -n "${TERMINAL:-}" ] && command -v "${TERMINAL}" >/dev/null 2>&1; then
    "${TERMINAL}" -e bash -lc "${sh_cmd}" >/dev/null 2>&1 & return 0
  fi

  local term
  for term in x-terminal-emulator gnome-terminal konsole xfce4-terminal kitty alacritty xterm; do
    if command -v "${term}" >/dev/null 2>&1; then
      case "${term}" in
        gnome-terminal)
          "${term}" -- bash -lc "${sh_cmd}" >/dev/null 2>&1 & return 0 ;;
        *)
          "${term}" -e bash -lc "${sh_cmd}" >/dev/null 2>&1 & return 0 ;;
      esac
    fi
  done
  return 1
}

case "$(uname -s)" in
  Darwin)
    # One retry: a Terminal.app that is mid-startup (or was quit moments ago)
    # has been seen dropping the first open request. Retrying can't double up
    # — a duplicate UI exits immediately via the pid-file guard.
    if { open_macos && verify_started; } || { open_macos && verify_started; }; then
      echo "claude-queue: opened the queue UI for session ${SESSION_ID}."
    else
      manual_fallback
    fi
    ;;
  Linux)
    if open_linux && verify_started; then
      echo "claude-queue: opened the queue UI for session ${SESSION_ID}."
    else
      manual_fallback
    fi
    ;;
  *)
    manual_fallback
    ;;
esac
